services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Toumoro\TmS3xclass\:
    resource: '../Classes/*'

  AUS\AusDriverAmazonS3\Service\MetaDataUpdateService: '@Toumoro\TmS3xclass\Service\MetaDataUpdateService'
